language: python

cache:
  - pip
  - ccache
  - directories:
      $HOME/mpi

matrix:
  include:
    # - os: linux
    #   python: "2.7"
    # - os: linux
    #   python: "3.4"
    - os: linux
      python: "3.5.1"

    # - os: osx
    #   language: generic
    #   env:
    #   - PYTHON_VERSION=2.7.10
    #   - PYENV_ROOT=~/.pyenv
    #   - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    # - os: osx
    #   language: generic
    #   env:
    #   - PYTHON_VERSION=3.4.3
    #   - PYENV_ROOT=~/.pyenv
    #   - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    # - os: osx
    #   language: generic
    #   env:
    #   - PYTHON_VERSION=3.5.1
    #   - PYENV_ROOT=~/.pyenv
    #   - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin

before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update >/dev/null;
      brew outdated pyenv || brew upgrade --quiet pyenv;
      brew install homebrew/boneyard/pyenv-pip-rehash;

      PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2" pyenv install -ks $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
      python --version;
    fi
  - /bin/bash .travis_build_mpi.sh

install:
  - pip install -U pip wheel
  - pip install cython
  - pip install nose hacking mock
  - pip install autopep8
  - pip install chainer
  - pip install mpi4py
  - python setup.py install --no-nccl

script:
  # - flake8
  # - flake8 --config=.flake8.cython
  # - autopep8 -r . --global-config .pep8 | tee check_autopep8
  # - test ! -s check_autopep8
  - for NP in 1 2; do PYTHONWARNINGS='ignore::FutureWarning,module::DeprecationWarning' mpiexsec -n ${NP} nosetests -a --with-doctest tests/install_tests; done
  # - cd tests
  # - PYTHONWARNINGS='ignore::FutureWarning,module::DeprecationWarning' nosetests -a '!gpu,!slow' --with-doctest chainer_tests
  # - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
  #     cd ..;
  #     READTHEDOCS=True python setup.py develop;
  #   fi

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - gfortran
      - libhdf5-serial-dev
      - liblapack-dev
      
